

# This file was *autogenerated* from the file Ch2Ex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2)
from sage.all import getrandbits
from timeit import timeit

def ex211():
    def helper(nbits):
        a, b = getrandbits(_sage_const_10 **nbits), getrandbits(_sage_const_10 **nbits)
        t = timeit(lambda: a*b, number=_sage_const_1 )
        return t
    
    for i in range(_sage_const_3 , _sage_const_8 ):
        print(str(i)+"-bit multiplication takes "+str(helper(i)) + " seconds")
    
    return _sage_const_0 

def ex213a():
    def helper(nbits):
        a, b = getrandbits(_sage_const_2 *_sage_const_10 **nbits), getrandbits(_sage_const_10 **nbits)
        t = timeit(lambda: a // b, number=_sage_const_1 )
        return t

    for i in range(_sage_const_3 , _sage_const_8 ):
        print(str(i)+"-bit division takes "+str(helper(i)) + " seconds")
    
def ex213b():
    def helper(nbits):
        a, b = getrandbits(_sage_const_10 **nbits), getrandbits(_sage_const_10 **nbits)
        t = timeit(lambda: gcd(a,b), number=_sage_const_1 )
        return t
    
    for i in range(_sage_const_3 , _sage_const_8 ):
        print(str(i)+"-bit gcd takes "+str(helper(i)) + " seconds")
    
if __name__ == "__main__":
    ex211()
    print("\n")
    ex213a()
    print("\n")
    ex213b()
    

