

# This file was *autogenerated* from the file Ch3Ex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_60 = Integer(60)
p = _sage_const_101 

def count_points_naive(q, f):
    """
    Count points on y^2 = f(x) over F_q using naive enumeration.
    
    For each x in F_q:
    - If f(x) = 0: contributes 1 point (x, 0)
    - If f(x) is a nonzero square: contributes 2 points (x, ±sqrt(f(x)))
    - If f(x) is not a square: contributes 0 points
    
    Plus points at infinity: for degree 7 (odd), there's 1 point at infinity.
    """
    Fq = GF(q)
    
    # Helper to count points for each x value
    def pts(x):
        fx = f(Fq(x))
        return _sage_const_1  if fx == _sage_const_0  else (_sage_const_2  if fx.is_square() else _sage_const_0 )
    
    # Affine points using list comprehension + point at infinity
    return sum(pts(x) for x in Fq) + _sage_const_1 

# Define the polynomial ring and the curve
R = PolynomialRing(ZZ, names=('x',)); (x,) = R._first_ngens(1)

# From y^2 + x^7 - x^6 + 6x^5 - 7x^4 + 5x^3 + x^2 - x + 1 = 0
# We get y^2 = -(x^7 - x^6 + 6x^5 - 7x^4 + 5x^3 + x^2 - x + 1)
f = -(x**_sage_const_7  - x**_sage_const_6  + _sage_const_6 *x**_sage_const_5  - _sage_const_7 *x**_sage_const_4  + _sage_const_5 *x**_sage_const_3  + x**_sage_const_2  - x + _sage_const_1 )

print("="*_sage_const_60 )
print("Point Counting on Genus 3 Hyperelliptic Curve")
print("="*_sage_const_60 )
print(f"\nCurve: y^2 = {f}")
print(f"Base prime: p = {p}")
print(f"Genus: g = 3")
print()

# Count points over F_p, F_p^2, F_p^3
for k in range(_sage_const_1 , _sage_const_4 ):
    q = p**k
    N = count_points_naive(q, f)
    print(f"#C(F_{{{p}}}^{k}) = #C(F_{{{q}}}) = {N}")

print()
print("="*_sage_const_60 )
print("Verification using SageMath's built-in HyperellipticCurve")
print("="*_sage_const_60 )

# Alternative: Use SageMath's built-in hyperelliptic curve functionality
for k in range(_sage_const_1 , _sage_const_4 ):
    q = p**k
    Fq = GF(q)
    Rq = PolynomialRing(Fq, names=('X',)); (X,) = Rq._first_ngens(1)
    
    # For HyperellipticCurve(f, h), we have y^2 + h*y = f
    # Our equation is y^2 = -(x^7 - x^6 + 6x^5 - 7x^4 + 5x^3 + x^2 - x + 1)
    # So h = 0 and f = -(X^7 - X^6 + 6*X^5 - 7*X^4 + 5*X^3 + X^2 - X + 1)
    fq = -(X**_sage_const_7  - X**_sage_const_6  + _sage_const_6 *X**_sage_const_5  - _sage_const_7 *X**_sage_const_4  + _sage_const_5 *X**_sage_const_3  + X**_sage_const_2  - X + _sage_const_1 )
    
    try:
        C = HyperellipticCurve(fq)
        N_sage = C.count_points(_sage_const_1 )[_sage_const_0 ]  # count_points returns list for extensions
        print(f"#C(F_{{{q}}}) = {N_sage} (SageMath HyperellipticCurve)")
    except Exception as e:
        print(f"F_{{{q}}}: Error using HyperellipticCurve: {e}")

print()
print("="*_sage_const_60 )
print("Computing a_k = q + 1 - N_k (trace-like quantities)")
print("="*_sage_const_60 )

for k in range(_sage_const_1 , _sage_const_4 ):
    q = p**k
    N = count_points_naive(q, f)
    a_k = q + _sage_const_1  - N
    print(f"a_{k} = {q} + 1 - {N} = {a_k}")

