

# This file was *autogenerated* from the file /home/janeshi/AWS26/Harvey-Class/Ch3Zeta.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_153 = Integer(153); _sage_const_9935 = Integer(9935); _sage_const_1029891 = Integer(1029891); _sage_const_51 = Integer(51); _sage_const_1167 = Integer(1167); _sage_const_15163 = Integer(15163); _sage_const_15 = Integer(15)
R = PolynomialRing(ZZ, names=('x',)); (x,) = R._first_ngens(1)

p = _sage_const_101 

f = -(x**_sage_const_7  - x**_sage_const_6  + _sage_const_6 *x**_sage_const_5  - _sage_const_7 *x**_sage_const_4  + _sage_const_5 *x**_sage_const_3  + x**_sage_const_2  - x + _sage_const_1 )

C = HyperellipticCurve(f)

def count_points():
    for k in range(_sage_const_1 , _sage_const_4 ):
        q = p**k
        Fq = GF(q)
        Rq = PolynomialRing(Fq, names=('X',)); (X,) = Rq._first_ngens(1)
        f_q = f.change_ring(Fq)
        C = HyperellipticCurve(f_q)
        print(f"#C(F_{{{q}}}) = {C.count_points(_sage_const_1 )[_sage_const_0 ]}")

def genus3Zeta(N1, N2, N3):
    powerPoly = N1*x + N2*x**_sage_const_2 /_sage_const_2  + N3*x**_sage_const_3 /_sage_const_3 
    zetaFunc = _sage_const_1  + (powerPoly)**_sage_const_1  + (_sage_const_1 /(factorial(_sage_const_2 )))*(powerPoly)**_sage_const_2  + (_sage_const_1 /(factorial(_sage_const_3 )))*(powerPoly)**_sage_const_3 

    c1 = zetaFunc[_sage_const_1 ]
    c2 = zetaFunc[_sage_const_2 ]
    c3 = zetaFunc[_sage_const_3 ]
     
    Lpoly = zetaFunc*(_sage_const_1 -x)*(_sage_const_1 -p*x)
    print(Lpoly)

    '''
    We ended up getting: 15163*x^3 + 1167*x^2 + 51*x + 1
    '''

    return Lpoly

ans = genus3Zeta(_sage_const_153 , _sage_const_9935 , _sage_const_1029891 )

a1, a2, a3 = _sage_const_51 , _sage_const_1167 , _sage_const_15163 


PS = PowerSeriesRing(QQ, default_prec=_sage_const_15 , names=('T',)); (T,) = PS._first_ngens(1)

Lpoly = p**_sage_const_3 *T**_sage_const_6  + p**_sage_const_2 *a1*T**_sage_const_5  + p*a2*T**_sage_const_4  + a3*T**_sage_const_3  + a2*T**_sage_const_2  + a1*T + _sage_const_1  
Zeta_exp = Lpoly/((_sage_const_1 -T)*(_sage_const_1 -p*T))
print("----------------------")
print(Zeta_exp)

