# We wish to compute (p-1)! mod p^2

# calculating remainder tree from bottom up.
# scrap this! can be generalized

'''
def compute_Q_k(p,t):
    #compute (k+1)(k+2)...(k+t) mod p^2
    R.<k> = PolynomialRing(Zmod(p^2))

    def recursive_helper(a,b):
        if a == b:
            return R(1)
        elif a == b-1:
            return R(k+a)
        else:
            m = a + (b-a)//2
            return recursive_helper(a,m) * recursive_helper(m,b)
    
    return recursive_helper(1,t+1)
'''


# This file was *autogenerated* from the file P6-1-2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10)
def linear_poly_acc(lin_list):
    def recursive_helper(a,b):
        if a == b:
            return R(_sage_const_1 )
        elif a == b-_sage_const_1 :
            return lin_list[a]
        else:
            m = a + (b-a)//_sage_const_2 
            return recursive_helper(a,m) * recursive_helper(m,b)
    
    return recursive_helper(_sage_const_0 , len(lin_list))

def compute_Q_k(p, t):
    R = PolynomialRing(Zmod(p**_sage_const_2 ), names=('k',)); (k,) = R._first_ngens(1)
    lin_list = [k+i for i in range(_sage_const_1 , t+_sage_const_1 )]
    return linear_poly_acc(lin_list)

print(compute_Q_k(_sage_const_11 , _sage_const_10 ))

#calculating remainder tree drom top down.

