

# This file was *autogenerated* from the file P6-Af.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_101 = Integer(101); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3)
import timeit as timeit_module 

class TreeNode:
    def __init__(self, val=_sage_const_0 , left=None, right=None):
        self.val = val
        self.left = left
        self.right = right



'''
Attempts to print a tree, but is terrible
'''

def print_tree(root):
    if root is None: 
        return 
    
    q = [root]
    while q:
        next_q = []
        for node in q:
            print(node.val, end=", ")
            if node.left: next_q.append(node.left)
            if node.right: next_q.append(node.right)
        print()
        q = next_q


'''
Given a list of objects, build the product tree. 
The product is not type dependent.
'''


def build_product_tree(lin_list):
    if not lin_list: return None
    
    def recursive_helper(a, b):
        if a == b: return None
        elif a == b-_sage_const_1 : return TreeNode(lin_list[a])
        else:
            m = a + (b-a)//_sage_const_2  
            left = recursive_helper(a, m)
            right = recursive_helper(m, b)
            left_val = left.val if left else _sage_const_1 
            right_val = right.val if right else _sage_const_1 
            return TreeNode(left_val * right_val, left, right)
    
    return recursive_helper(_sage_const_0 , len(lin_list))

def fast_product(lin_list):
    print(lin_list)
    product_tree = build_product_tree(lin_list)
    return product_tree.val


def remainder_tree(root_element, prod_tree_root):
    leaf_val_list = []
    def recursive_helper(element, prod_tree): 
        if prod_tree is None: return None
        root_val = element % prod_tree.val 
        left_rem = recursive_helper(root_val, prod_tree.left)
        right_rem = recursive_helper(root_val, prod_tree.right)
        if left_rem is None and right_rem is None:
            leaf_val_list.append(root_val)
        return TreeNode(root_val, left_rem, right_rem)
    
    rem_tree = recursive_helper(root_element, prod_tree_root)
    return rem_tree, leaf_val_list

def evaluation_tree(evaluation_poly, values, p):
    R = evaluation_poly.parent()
    k = R.gen()
    leaves = [k-R(i) for i in values]
    prod_tree = build_product_tree(leaves)
    rem_tree, leaf_val_list = remainder_tree(evaluation_poly, prod_tree)
    return leaf_val_list

def generate_T_matrix(p, k_val, d, m, F_coeffs):
    R = PolynomialRing(Zmod(p**_sage_const_2 ), names=('k',)); (k,) = R._first_ngens(1)
    print(type(R(k_val)))
    print(type(F_coeffs[_sage_const_0 ]))
    sub = R(k_val) * F_coeffs[_sage_const_0 ]
    M = matrix(k_val.parent(), d, d)
    for i in range(_sage_const_1 ,d):
        M[i,i-_sage_const_1 ] = sub
    
    for i in range(d):
        j = d - i
        M[i, d-_sage_const_1 ] = (R(j*(m+_sage_const_1 )) - R(k_val)) * F_coeffs[j]

    return M


def compute_T_products(p, k0, s, F_coeffs, m, d, R):
    t = floor(sqrt(s))
    print("t", t)
    print("s", s)
    print(type(s), type(t))
    t_prime = s - t**_sage_const_2 

    
    k = R.gen()

    # the fast matrix product T_(k+1)...T_(k+t)
    T_matrices = [generate_T_matrix(p,k+i,d,m,F_coeffs) for i in range(_sage_const_1 ,t+_sage_const_1 )]
    T_product = fast_product(T_matrices)
    values = [k0 + i*t for i in range(_sage_const_0 , t)]
    print("values", values)

    nrows, ncols = T_product.nrows(), T_product.ncols()
    entry_evals = [evaluation_tree(T_product[i,j], values, p) for i in range(nrows) for j in range(ncols)]

    mat_vals = [
        matrix(R.base_ring(), nrows, ncols, [entry[k] for entry in entry_evals]) 
        for k in range(len(values))
    ]
    
    T_matrices_left = [generate_T_matrix(p, idx, d, m, F_coeffs) for idx in range(k0+t**_sage_const_2 +_sage_const_1 , k0+s+_sage_const_1 )]

    total_mat_prod_t_squared = fast_product(mat_vals)
    if T_matrices_left:
        total_mat_prod_leftover = fast_product(T_matrices_left)
        total_mat_prod = total_mat_prod_t_squared * total_mat_prod_leftover
    else:
        total_mat_prod = total_mat_prod_t_squared
    print("this should be all integers")
    print(total_mat_prod)
    return total_mat_prod

# product of (k0+1, k0+2, ..., k0+s)
def compute_int_products(p, k0, s, R):
    t = floor(sqrt(s))
    t_prime = s - t**_sage_const_2 
    k = R.gen()
    
    val_polys = [R(k + j) for j in range(_sage_const_1 ,t+_sage_const_1 )]
    val_prod = fast_product(val_polys)
    
    values = [R(k0 + j*t) for j in range(_sage_const_0 , t)]
    evals = evaluation_tree(val_prod, values, p)
    

    values_left = [R(j) for j in range(k0+t**_sage_const_2 +_sage_const_1 , k0+s+_sage_const_1 )]
    print("debug - following shall be ints")
    print(evals)
    print(values_left)
    print(product(evals) * product(values_left))
    print("this vector all int", product(evals) * product(values_left))
    return product(evals) * product(values_left)

def fake_inverse(x, p, R):
    if Integer(x) % p != _sage_const_0 :
        return x**(-_sage_const_1 )
    else:
        fake_inverse = Integer(x)/p
        print("fake inverse!", fake_inverse)
        return (Zmod(p**_sage_const_2 )(fake_inverse))**(-_sage_const_1 )


'''
Goal #1 is to just compute as it without reducing the extra O(g) factor
'''
    
def compute_A_f(F_coeffs, p):
    
    d = len(F_coeffs)-_sage_const_1 
    g = (d-_sage_const_1 ) // _sage_const_2 
    m = (p-_sage_const_1 )//_sage_const_2 
    R = PolynomialRing(Zmod(p**_sage_const_2 ), names=('k',)); (k,) = R._first_ngens(1)
    k = R.gen()
    F_coeffs = [R(c) for c in F_coeffs]
    F0 = R(F_coeffs[_sage_const_0 ])

    acc = Matrix(R, _sage_const_1 , d)
    A_f = []
    
    for i in range(_sage_const_0 , g):
        if i == _sage_const_0 :
            acc[_sage_const_0 , -_sage_const_1 ] = R(F0**m)
            print(acc, "acc1")
        else:
            print("pre-multiplying, round ",i)
            print(acc)
            T_single = generate_T_matrix(p, p*i, d, m, F_coeffs)
            print("computed the T_single", T_single)
            print(T_single)
            acc = acc * T_single
            print("computed the acc", acc)
            print(type(i*p*F0))
            print("inverting 1")
            print(i*p*F0)
            to_invert = i*p*F0
            inverted = Zmod(p**_sage_const_2 )(fake_inverse(to_invert, p, R))
            acc = acc * inverted
            print("gebug", "i=", i)
            print(acc, "acc2")
        acc = acc * compute_T_products(p, i*p+_sage_const_1 , p-_sage_const_1 , F_coeffs, m, d, R)
        print("acc done multiplying")
        print(type(compute_int_products(p, i*p+_sage_const_1 , p-_sage_const_1 , R)))

        print("inverting 2")
        print("this should be an int", compute_int_products(p, i*p+_sage_const_1 , p-_sage_const_1 , R))

        # p-adic inversion is kind of broken here!
        to_invert = (Zmod(p**_sage_const_2 )(compute_int_products(p, i*p+_sage_const_1 , p-_sage_const_1 , R)))
        acc = acc * (Zmod(p**_sage_const_2 )(fake_inverse(to_invert, p, R)))
        print("g = ",g)
        print("acc is", [acc[_sage_const_0 ][(-g):]])
        A_f.append(acc[_sage_const_0 ][(-g):])


    print("computed A_f")
    print(A_f%p)

    return A_f



p = _sage_const_101 
R = PolynomialRing(ZZ, names=('x',)); (x,) = R._first_ngens(1)
f = -(x**_sage_const_7  - x**_sage_const_6  + _sage_const_6 *x**_sage_const_5  - _sage_const_7 *x**_sage_const_4  + _sage_const_5 *x**_sage_const_3  + x**_sage_const_2  - x + _sage_const_1 )

compute_A_f(f.list(), p)

