

# This file was *autogenerated* from the file P6-tree.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_11 = Integer(11); _sage_const_16 = Integer(16); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20)
class TreeNode:
    def __init__(self, val=_sage_const_0 , left=None, right=None):
        self.val = val
        self.left = left
        self.right = right
    

def print_tree(root):
    if root is None: 
        return 
    
    q = [root]
    while q:
        next_q = []
        for node in q:
            print(node.val, end=", ")
            if node.left: next_q.append(node.left)
            if node.right: next_q.append(node.right)
        print()
        q = next_q


def build_product_tree(lin_list):
    if not lin_list: return None
    
    def recursive_helper(a, b):
        if a == b: return None
        elif a == b-_sage_const_1 : return TreeNode(lin_list[a])
        else:
            m = a + (b-a)//_sage_const_2  
            left = recursive_helper(a, m)
            right = recursive_helper(m, b)
            left_val = left.val if left else _sage_const_1 
            right_val = right.val if right else _sage_const_1 
            return TreeNode(left_val * right_val, left, right)
    
    return recursive_helper(_sage_const_0 , len(lin_list))

def compute_Q_k(p, t):
    R = PolynomialRing(Zmod(p**_sage_const_2 ), names=('k',)); (k,) = R._first_ngens(1)
    lin_list = [k+i for i in range(_sage_const_1 , t+_sage_const_1 )]
    tree = build_product_tree(lin_list)
    print_tree(tree)
    return tree, tree.val

tree, res = compute_Q_k(_sage_const_11 , _sage_const_16 )

def remainder_tree(root_poly, prod_tree_root):
    leaf_val_list = []
    def recursive_helper(poly, prod_tree): 
        if prod_tree is None: return None
        root_val = poly % prod_tree.val 
        left_rem = recursive_helper(root_val, prod_tree.left)
        right_rem = recursive_helper(root_val, prod_tree.right)
        if left_rem is None and right_rem is None:
            leaf_val_list.append(root_val)
        return TreeNode(root_val, left_rem, right_rem)
    
    rem_tree = recursive_helper(root_poly, prod_tree_root)
    return rem_tree, leaf_val_list

def compute_factorial(p):
    s = p-_sage_const_1 
    t = floor(sqrt(s))
    t_prime = s - t**_sage_const_2 


    R = PolynomialRing(Zmod(p**_sage_const_2 ), names=('k',)); (k,) = R._first_ngens(1)

    tree, Q_k = compute_Q_k(p, t)
    prod_tree = build_product_tree([k-i*t for i in range(_sage_const_0 , t)])

    rem_tree, leaf_val_list = remainder_tree(Q_k, prod_tree)
    return product(leaf_val_list) * product(i for i in range(t**_sage_const_2 +_sage_const_1 , p))

import timeit as timeit_module

def test_two_methods():
    exponents = [i for i in range(_sage_const_10 ,_sage_const_20 )]

    for exp in exponents:
        p = next_prime(_sage_const_2 **exp)
        print(p)
        print(compute_factorial(p))
        print(factorial(p-_sage_const_1 ) % p**_sage_const_2 )

        print("Tree method:")
        t1 = %timeit compute_factorial(p)
        print(t1)
        print("Direct method:")
        t2 = %timeit factorial(p-_sage_const_1 ) % p**_sage_const_2 
        print(t2)
        print("\n")

