name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run tests
        run: sage tests/runtests.sage
